local tailwind = require('chroma.tailwind')

return function() 
  if vim.o.background == 'light' then return {
    red =     tailwind.red_500,
    orange =  tailwind.orange_500,
    yellow =  tailwind.yellow_500,
    green =   tailwind.green_500,
    cyan =    tailwind.cyan_500,
    blue =    tailwind.blue_500,
    magenta = tailwind.purple_500,
    black =   tailwind.gray_950,
    bright_red =     tailwind.red_600,
    bright_orange =  tailwind.orange_600,
    bright_yellow =  tailwind.yellow_600,
    bright_green =   tailwind.green_600,
    bright_cyan =    tailwind.cyan_600,
    bright_blue =    tailwind.blue_600,
    bright_magenta = tailwind.purple_600,
    white =          tailwind.gray_50,
    dark_red =     tailwind.red_400,
    dark_orange =  tailwind.orange_400,
    dark_yellow =  tailwind.yellow_400,
    dark_green =   tailwind.green_400,
    dark_cyan =    tailwind.cyan_400,
    dark_blue =    tailwind.blue_400,
    dark_magenta = tailwind.purple_400,
    gray =   tailwind.gray_500,
    silver = tailwind.gray_300,

    bg         = tailwind.gray_50,
    fg         = tailwind.gray_900,
    cursorline = tailwind.gray_200,
    selection  = tailwind.gray_200,
    linenr     = tailwind.gray_700,
    comment    = tailwind.gray_400,
    nontext    = tailwind.gray_300,

    keyword    = tailwind.purple_700,
    Function   = tailwind.blue_700,
    string     = tailwind.lime_700,
    constant   = tailwind.fuchsia_800,
    type       = tailwind.amber_700,
    number     = tailwind.orange_600,
    boolean    = tailwind.rose_600,
    operator   = tailwind.cyan_800,
    variable   = tailwind.gray_950,
    bracket    = tailwind.gray_600,

    cursor     = tailwind.gray_800,
    visual     = tailwind.gray_300,
    statusline = tailwind.gray_300,
    fold       = tailwind.emerald_800,
    menubg     = tailwind.zinc_50,
    menuborder = tailwind.gray_300,
    menusel    = tailwind.gray_200,
    menuthumb  = tailwind.gray_300,

    diag_error = tailwind.red_500,
    diag_warn  = tailwind.amber_500,
    diag_info  = tailwind.blue_500,
    diag_hint  = tailwind.gray_500,

  } else return {
      red =     tailwind.red_500,
      orange =  tailwind.orange_500,
      yellow =  tailwind.yellow_500,
      green =   tailwind.green_500,
      cyan =    tailwind.cyan_500,
      blue =    tailwind.blue_500,
      magenta = tailwind.purple_500,
      black =   tailwind.gray_950,
      bright_red =     tailwind.red_400,
      bright_orange =  tailwind.orange_400,
      bright_yellow =  tailwind.yellow_400,
      bright_green =   tailwind.green_400,
      bright_cyan =    tailwind.cyan_400,
      bright_blue =    tailwind.blue_400,
      bright_magenta = tailwind.purple_400,
      white =          tailwind.gray_50,
      dark_red =     tailwind.red_600,
      dark_orange =  tailwind.orange_600,
      dark_yellow =  tailwind.yellow_600,
      dark_green =   tailwind.green_600,
      dark_cyan =    tailwind.cyan_600,
      dark_blue =    tailwind.blue_600,
      dark_magenta = tailwind.purple_600,
      gray =   tailwind.gray_500,
      silver = tailwind.gray_300,

      bg         = nil,
      fg         = tailwind.gray_50,
      cursorline = tailwind.gray_950,
      selection  = tailwind.gray_800,
      linenr     = tailwind.gray_700,
      comment    = tailwind.gray_500,
      nontext    = tailwind.gray_400,

      keyword    = tailwind.purple_400,
      Function   = tailwind.blue_400,
      string     = tailwind.lime_300,
      constant   = tailwind.pink_300,
      type       = tailwind.amber_300,
      number     = tailwind.orange_400,
      boolean    = tailwind.red_400,
      operator   = tailwind.cyan_200,
      variable   = tailwind.gray_50,
      bracket    = tailwind.gray_400,

      cursor     = tailwind.gray_100,
      visual     = tailwind.gray_700,
      statusline = tailwind.gray_950,
      fold       = tailwind.emerald_300,
      menubg     = nil,
      menuborder = tailwind.gray_500,
      menusel    = tailwind.gray_800,
      menuthumb  = tailwind.gray_700,

      diag_error = tailwind.red_500,
      diag_warn  = tailwind.amber_500,
      diag_info  = tailwind.sky_500,
      diag_hint  = tailwind.gray_300,
    } end
end
